import type { Metadata } from "next";
import NavBar from "@/components/organisms/NavBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "PayHome",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="jp">
      <body>
        <NavBar isCompanyLoggedIn={true} />
        {children}
      </body>
    </html>
  );
}
